//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComment
    {
        public int CommentID { get; set; }
        public int Comment_MemberID { get; set; }
        public int Comment_MovieID { get; set; }
        public string CommentTitle { get; set; }
        public string CommentContent { get; set; }
        public Nullable<int> CommentUpCount { get; set; }
        public Nullable<int> CommentDownCount { get; set; }
        public Nullable<System.DateTime> CommentDate { get; set; }
        public Nullable<bool> CommentIsApproved { get; set; }
    
        public virtual tblMember tblMember { get; set; }
        public virtual tblMovie tblMovie { get; set; }
    }
}
