//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCast
    {
        public int CastID { get; set; }
        public int Cast_MovieID { get; set; }
        public int Cast_PeopleID { get; set; }
        public int Cast_RoleID { get; set; }
        public string CastCharacterName { get; set; }
    
        public virtual tblMovie tblMovie { get; set; }
        public virtual tblPeople tblPeople { get; set; }
        public virtual tblRoles tblRoles { get; set; }
    }
}
