//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMovie
    {
        public tblMovie()
        {
            this.tblCast = new HashSet<tblCast>();
            this.tblComment = new HashSet<tblComment>();
            this.tblMovieFavList = new HashSet<tblMovieFavList>();
            this.tblMovieRating = new HashSet<tblMovieRating>();
            this.tblMovieType = new HashSet<tblMovieType>();
            this.tblCountry = new HashSet<tblCountry>();
            this.tblLanguage = new HashSet<tblLanguage>();
        }
    
        public int MovieID { get; set; }
        public string MovieName { get; set; }
        public Nullable<System.DateTime> MovieReleaseDate { get; set; }
        public string MovieSynopsis { get; set; }
        public Nullable<int> MovieRunTimeMinutes { get; set; }
        public Nullable<decimal> MovieBoxOfficeDollars { get; set; }
        public Nullable<int> MovieRatingIMDB { get; set; }
        public byte[] MoviePhoto { get; set; }
    
        public virtual ICollection<tblCast> tblCast { get; set; }
        public virtual ICollection<tblComment> tblComment { get; set; }
        public virtual ICollection<tblMovieFavList> tblMovieFavList { get; set; }
        public virtual ICollection<tblMovieRating> tblMovieRating { get; set; }
        public virtual ICollection<tblMovieType> tblMovieType { get; set; }
        public virtual ICollection<tblCountry> tblCountry { get; set; }
        public virtual ICollection<tblLanguage> tblLanguage { get; set; }
    }
}
