//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMovieType
    {
        public int MovieType_MovieID { get; set; }
        public int MovieType_TypeID { get; set; }
        public string MovieType_Name { get; set; }
    
        public virtual tblMovie tblMovie { get; set; }
        public virtual tblType tblType { get; set; }
    }
}
