//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPeople
    {
        public tblPeople()
        {
            this.tblCast = new HashSet<tblCast>();
            this.tblPeopleFavList = new HashSet<tblPeopleFavList>();
        }
    
        public int PeopleID { get; set; }
        public string PeopleName { get; set; }
        public Nullable<System.DateTime> PeopleDOB { get; set; }
        public byte[] PeoplePhoto { get; set; }
    
        public virtual ICollection<tblCast> tblCast { get; set; }
        public virtual ICollection<tblPeopleFavList> tblPeopleFavList { get; set; }
    }
}
