//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebProje.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebProje.Resources.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ad.
        /// </summary>
        public static string Ad {
            get {
                return ResourceManager.GetString("Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adınızı giriniz.
        /// </summary>
        public static string AdGiriniz {
            get {
                return ResourceManager.GetString("AdGiriniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aksiyon.
        /// </summary>
        public static string Aksiyon {
            get {
                return ResourceManager.GetString("Aksiyon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anasayfa.
        /// </summary>
        public static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ana Sponsorlar.
        /// </summary>
        public static string AnaSponsorlar {
            get {
                return ResourceManager.GetString("AnaSponsorlar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ara.
        /// </summary>
        public static string Ara {
            get {
                return ResourceManager.GetString("Ara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belgesel.
        /// </summary>
        public static string Belgesel {
            get {
                return ResourceManager.GetString("Belgesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgi.
        /// </summary>
        public static string Bilgi {
            get {
                return ResourceManager.GetString("Bilgi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilim-Kurgu.
        /// </summary>
        public static string BilimKurgu {
            get {
                return ResourceManager.GetString("BilimKurgu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biyografi.
        /// </summary>
        public static string Biyografi {
            get {
                return ResourceManager.GetString("Biyografi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum Tarihi.
        /// </summary>
        public static string DogumTarihi {
            get {
                return ResourceManager.GetString("DogumTarihi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doğum tarihinizi giriniz.
        /// </summary>
        public static string DogumTarihiGiriniz {
            get {
                return ResourceManager.GetString("DogumTarihiGiriniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dram.
        /// </summary>
        public static string Dram {
            get {
                return ResourceManager.GetString("Dram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Posta.
        /// </summary>
        public static string Eposta {
            get {
                return ResourceManager.GetString("Eposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-postanızı giriniz.
        /// </summary>
        public static string EpostaGiriniz {
            get {
                return ResourceManager.GetString("EpostaGiriniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu alana erişim yetkiniz bulunmamaktadır !.
        /// </summary>
        public static string ErisimYetkisiYokMesaj {
            get {
                return ResourceManager.GetString("ErisimYetkisiYokMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorilere Ekle.
        /// </summary>
        public static string FavoriEkle {
            get {
                return ResourceManager.GetString("FavoriEkle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film favorilerinize başarıyla eklendi !...
        /// </summary>
        public static string FavoriEklendiMesaj {
            get {
                return ResourceManager.GetString("FavoriEklendiMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favori Fimlerim.
        /// </summary>
        public static string FavoriFimlerim {
            get {
                return ResourceManager.GetString("FavoriFimlerim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorilerim.
        /// </summary>
        public static string Favorilerim {
            get {
                return ResourceManager.GetString("Favorilerim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu film zaten favorileriniz arasında !.
        /// </summary>
        public static string FavoriZatenEkliMesaj {
            get {
                return ResourceManager.GetString("FavoriZatenEkliMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Detayları.
        /// </summary>
        public static string FilmDetay {
            get {
                return ResourceManager.GetString("FilmDetay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film İstek.
        /// </summary>
        public static string Filmistek {
            get {
                return ResourceManager.GetString("Filmistek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filmler.
        /// </summary>
        public static string Filmler {
            get {
                return ResourceManager.GetString("Filmler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film silme işlemi başarılı..
        /// </summary>
        public static string FilmSilindiMesaj {
            get {
                return ResourceManager.GetString("FilmSilindiMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Film Türleri.
        /// </summary>
        public static string FilmTurleri {
            get {
                return ResourceManager.GetString("FilmTurleri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotoğraf.
        /// </summary>
        public static string Foto {
            get {
                return ResourceManager.GetString("Foto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelişmiş Arama.
        /// </summary>
        public static string GelismisArama {
            get {
                return ResourceManager.GetString("GelismisArama", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerilim.
        /// </summary>
        public static string Gerilim {
            get {
                return ResourceManager.GetString("Gerilim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş.
        /// </summary>
        public static string Giris {
            get {
                return ResourceManager.GetString("Giris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filme Git.
        /// </summary>
        public static string GitFilm {
            get {
                return ResourceManager.GetString("GitFilm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geri.
        /// </summary>
        public static string GitGeri {
            get {
                return ResourceManager.GetString("GitGeri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hakkımızda.
        /// </summary>
        public static string Hakkimizda {
            get {
                return ResourceManager.GetString("Hakkimizda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hasılat.
        /// </summary>
        public static string Hasilat {
            get {
                return ResourceManager.GetString("Hasilat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hesabım.
        /// </summary>
        public static string Hesabim {
            get {
                return ResourceManager.GetString("Hesabim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İletişim.
        /// </summary>
        public static string İletisim {
            get {
                return ResourceManager.GetString("İletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komedi.
        /// </summary>
        public static string Komedi {
            get {
                return ResourceManager.GetString("Komedi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korku.
        /// </summary>
        public static string Korku {
            get {
                return ResourceManager.GetString("Korku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macera.
        /// </summary>
        public static string Macera {
            get {
                return ResourceManager.GetString("Macera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Müzikal.
        /// </summary>
        public static string Muzikal {
            get {
                return ResourceManager.GetString("Muzikal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Özet.
        /// </summary>
        public static string Ozet {
            get {
                return ResourceManager.GetString("Ozet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Parola {
            get {
                return ResourceManager.GetString("Parola", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Romantik.
        /// </summary>
        public static string Romantik {
            get {
                return ResourceManager.GetString("Romantik", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Savaş.
        /// </summary>
        public static string Savas {
            get {
                return ResourceManager.GetString("Savas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre.
        /// </summary>
        public static string Sifre {
            get {
                return ResourceManager.GetString("Sifre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifrenizi giriniz.
        /// </summary>
        public static string SifreGiriniz {
            get {
                return ResourceManager.GetString("SifreGiriniz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sil.
        /// </summary>
        public static string Sil {
            get {
                return ResourceManager.GetString("Sil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Kullanımı.
        /// </summary>
        public static string SiteKullanimi {
            get {
                return ResourceManager.GetString("SiteKullanimi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suç.
        /// </summary>
        public static string Suc {
            get {
                return ResourceManager.GetString("Suc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Süre.
        /// </summary>
        public static string Sure {
            get {
                return ResourceManager.GetString("Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bizi Takip Edin!.
        /// </summary>
        public static string TakipEdin {
            get {
                return ResourceManager.GetString("TakipEdin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tüm hakları saklıdır..
        /// </summary>
        public static string Telif {
            get {
                return ResourceManager.GetString("Telif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Türe Göre Fimler.
        /// </summary>
        public static string TureGoreFimler {
            get {
                return ResourceManager.GetString("TureGoreFimler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Giriş.
        /// </summary>
        public static string UyeGiris {
            get {
                return ResourceManager.GetString("UyeGiris", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üyeliğiniz başarıyla tamamlandı !.
        /// </summary>
        public static string UyelikTamamMesaj {
            get {
                return ResourceManager.GetString("UyelikTamamMesaj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Üye Ol.
        /// </summary>
        public static string UyeOl {
            get {
                return ResourceManager.GetString("UyeOl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yapım Yılı.
        /// </summary>
        public static string YapimYil {
            get {
                return ResourceManager.GetString("YapimYil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yorumlarım.
        /// </summary>
        public static string Yorumlarim {
            get {
                return ResourceManager.GetString("Yorumlarim", resourceCulture);
            }
        }
    }
}
